// Generated by @decocms/blocks-migrate from a v7 site. It's your code now: edit it freely.
// Each block has a short name plus an alias under every v7 name saved content stores
// (see /next/renames-and-migrations).
import type { Blocks, Route, Seo } from "@decocms/blocks";
import blogAuthor from "../src/vendor/blog/loaders/Author";
import blogBlogPostPage from "../src/vendor/blog/loaders/BlogPostPage";
import blogBlogpost from "../src/vendor/blog/loaders/Blogpost";
import blogCategory from "../src/vendor/blog/loaders/Category";

/** What a section block returns: the component to render and its props (/next/rendering). */
export interface BlockDescriptor {
  component: string;
  props: unknown;
}

/** A page with its blocks resolved. */
export interface ResolvedPage extends Route {
  seo?: Seo;
  sections: BlockDescriptor[];
}

/** A v7 section's saved props: its loader's input when it has one, else its component's props. */
type PropsOf<M> = M extends { loader: (props: infer P, ...rest: any[]) => unknown }
  ? P
  : M extends { default: (props: infer P, ...rest: any[]) => unknown }
    ? P
    : Record<string, never>;

const section =
  <M>(component: string) =>
  (props: PropsOf<M>): BlockDescriptor => ({ component, props });

const blogAuthors = section<typeof import("../src/sections/Blog/BlogAuthors")>("blog-authors");
const blogHeader = section<typeof import("../src/sections/Blog/BlogHeader")>("blog-header");
const blogHome = section<typeof import("../src/sections/Blog/BlogHome")>("blog-home");
const blogPostSection = section<typeof import("../src/sections/Blog/BlogPostSection")>("blog-post-section");
const blogSearch = section<typeof import("../src/sections/Blog/BlogSearch")>("blog-search");
const blogTopics = section<typeof import("../src/sections/Blog/BlogTopics")>("blog-topics");
const blockImage = section<typeof import("../src/sections/Blog/blocks/BlockImage")>("block-image");
const callToAction = section<typeof import("../src/sections/Blog/blocks/CallToAction")>("call-to-action");
const callout = section<typeof import("../src/sections/Blog/blocks/Callout")>("callout");
const checklist = section<typeof import("../src/sections/Blog/blocks/Checklist")>("checklist");
const code = section<typeof import("../src/sections/Blog/blocks/Code")>("code");
const divider = section<typeof import("../src/sections/Blog/blocks/Divider")>("divider");
const faq = section<typeof import("../src/sections/Blog/blocks/Faq")>("faq");
const heading = section<typeof import("../src/sections/Blog/blocks/Heading")>("heading");
const list = section<typeof import("../src/sections/Blog/blocks/List")>("list");
const paragraph = section<typeof import("../src/sections/Blog/blocks/Paragraph")>("paragraph");
const quote = section<typeof import("../src/sections/Blog/blocks/Quote")>("quote");
const steps = section<typeof import("../src/sections/Blog/blocks/Steps")>("steps");
const video = section<typeof import("../src/sections/Blog/blocks/Video")>("video");
const seoBlogAuthor = section<typeof import("../src/sections/Seo/SeoBlogAuthor")>("seo-blog-author");
const seoBlogCategory = section<typeof import("../src/sections/Seo/SeoBlogCategory")>("seo-blog-category");
const seoBlogPost = section<typeof import("../src/sections/Seo/SeoBlogPost")>("seo-blog-post");

export default {
  page: (input: ResolvedPage) => input,
  "blog-author": blogAuthor,
  "blog/loaders/Author.ts": blogAuthor,
  "blog-blog-post-page": blogBlogPostPage,
  "blog/loaders/BlogPostPage.ts": blogBlogPostPage,
  "blog-blogpost": blogBlogpost,
  "blog/loaders/Blogpost.ts": blogBlogpost,
  "blog-category": blogCategory,
  "blog/loaders/Category.ts": blogCategory,
  "blog-authors": blogAuthors,
  "site/sections/Blog/BlogAuthors.tsx": blogAuthors,
  "blog-header": blogHeader,
  "site/sections/Blog/BlogHeader.tsx": blogHeader,
  "blog-home": blogHome,
  "site/sections/Blog/BlogHome.tsx": blogHome,
  "blog-post-section": blogPostSection,
  "site/sections/Blog/BlogPostSection.tsx": blogPostSection,
  "blog-search": blogSearch,
  "site/sections/Blog/BlogSearch.tsx": blogSearch,
  "blog-topics": blogTopics,
  "site/sections/Blog/BlogTopics.tsx": blogTopics,
  "block-image": blockImage,
  "site/sections/Blog/blocks/BlockImage.tsx": blockImage,
  "call-to-action": callToAction,
  "site/sections/Blog/blocks/CallToAction.tsx": callToAction,
  "callout": callout,
  "site/sections/Blog/blocks/Callout.tsx": callout,
  "checklist": checklist,
  "site/sections/Blog/blocks/Checklist.tsx": checklist,
  "code": code,
  "site/sections/Blog/blocks/Code.tsx": code,
  "divider": divider,
  "site/sections/Blog/blocks/Divider.tsx": divider,
  "faq": faq,
  "site/sections/Blog/blocks/Faq.tsx": faq,
  "heading": heading,
  "site/sections/Blog/blocks/Heading.tsx": heading,
  "list": list,
  "site/sections/Blog/blocks/List.tsx": list,
  "paragraph": paragraph,
  "site/sections/Blog/blocks/Paragraph.tsx": paragraph,
  "quote": quote,
  "site/sections/Blog/blocks/Quote.tsx": quote,
  "steps": steps,
  "site/sections/Blog/blocks/Steps.tsx": steps,
  "video": video,
  "site/sections/Blog/blocks/Video.tsx": video,
  "seo-blog-author": seoBlogAuthor,
  "site/sections/Seo/SeoBlogAuthor.tsx": seoBlogAuthor,
  "seo-blog-category": seoBlogCategory,
  "site/sections/Seo/SeoBlogCategory.tsx": seoBlogCategory,
  "seo-blog-post": seoBlogPost,
  "site/sections/Seo/SeoBlogPost.tsx": seoBlogPost,
} satisfies Blocks;
