// Auto-generated by @decocms/blocks-cli/scripts/generate-loaders.ts
// Do not edit manually. Run `npm run generate:loaders` to update.
//
// Loader entries route through createLoaderEntry so their cache/cacheKey
// exports drive single-flight dedup (concurrent identical calls in one
// render collapse to one upstream call). Actions stay plain pass-throughs
// (never cached/deduped). Custom-wired entries should be excluded via
// --exclude and added manually in setup.ts.

import { createLoaderEntry } from "@decocms/blocks/sdk/cachedLoader";

export const siteLoaders: Record<string, (props: any, request?: Request) => Promise<any>> = {
  "site/loaders/BlogpostList": createLoaderEntry("site/loaders/BlogpostList", () => import("../src/loaders/BlogpostList")),
  "site/loaders/BlogpostList.ts": createLoaderEntry("site/loaders/BlogpostList", () => import("../src/loaders/BlogpostList")),
};
