// Auto-generated by @decocms/blocks-cli/scripts/generate-sections.ts
// Do not edit manually. Add convention exports to your section files instead.
//
// Supported conventions:
//   export const eager = true       → prefer eager (defers past fold threshold)
//   export const neverDefer = true  → ALWAYS eager, ignores fold threshold
//   export const cache = "listing"  → SWR-cached section loader results
//   export const layout = true      → cached as layout (Header, Footer, Theme)
//   export const sync = true        → bundled synchronously (not lazy-loaded)
//   export const clientOnly = true  → skip SSR (client-only rendering)
//   export const seo = true         → SEO section (provides page head data)
//   export function LoadingFallback → skeleton shown while section loads
//   export const renderJson = false → drop section from ?renderJson (mobile)
//   export const renderJson = (p)=> → project props for ?renderJson (mobile)

import * as _sync0 from "../src/sections/Blog/BlogAuthors";
import * as _sync1 from "../src/sections/Blog/BlogHeader";
import * as _sync2 from "../src/sections/Blog/BlogHome";
import * as _sync3 from "../src/sections/Blog/BlogPostSection";
import * as _sync4 from "../src/sections/Blog/BlogSearch";
import * as _sync5 from "../src/sections/Blog/BlogTopics";
import * as _sync6 from "../src/sections/Seo/SeoBlogAuthor";

export interface SectionMetaEntry {
  eager?: boolean;
  neverDefer?: boolean;
  deferred?: boolean;
  cache?: string;
  layout?: boolean;
  sync?: boolean;
  clientOnly?: boolean;
  seo?: boolean;
  hasLoadingFallback?: boolean;
  renderJson?: false;
  hasRenderJson?: boolean;
}

export const sectionMeta: Record<string, SectionMetaEntry> = {
  "site/sections/Blog/BlogAuthors.tsx": { eager: true, sync: true },
  "site/sections/Blog/BlogHeader.tsx": { eager: true, sync: true, layout: true },
  "site/sections/Blog/BlogHome.tsx": { eager: true, sync: true },
  "site/sections/Blog/BlogPostSection.tsx": { eager: true, sync: true },
  "site/sections/Blog/BlogSearch.tsx": { eager: true, sync: true },
  "site/sections/Blog/BlogTopics.tsx": { eager: true, sync: true },
  "site/sections/Seo/SeoBlogAuthor.tsx": { seo: true, sync: true },
};

export const syncComponents: Record<string, any> = {
  "site/sections/Blog/BlogAuthors.tsx": _sync0,
  "site/sections/Blog/BlogHeader.tsx": _sync1,
  "site/sections/Blog/BlogHome.tsx": _sync2,
  "site/sections/Blog/BlogPostSection.tsx": _sync3,
  "site/sections/Blog/BlogSearch.tsx": _sync4,
  "site/sections/Blog/BlogTopics.tsx": _sync5,
  "site/sections/Seo/SeoBlogAuthor.tsx": _sync6,
};

export const loadingFallbacks: Record<string, React.ComponentType<any>> = {};

export const renderJsons: Record<string, any> = {};
