/**
 * Generate src/server/cms/site-globals.gen.ts from blocks.gen.json.
 *
 * Workaround for `decocms/deco-start#233` — the framework's vite plugin stubs
 * `blocks.gen.ts` to `{}` on the client bundle (saves ~10 MB), so the
 * `withSiteGlobals.wrapLoader` call that TanStack re-runs on the client
 * during hydration ends up resolving against an empty registry and drops
 * the site globals (Theme, Session, ButtonHelp, …) → React 19 fatal
 * hydration mismatch.
 *
 * This script extracts ONLY the blocks needed to resolve `site.theme +
 * site.global + site.pageSections` (typically the site block, the theme
 * block, and one or two helper blocks like `ButtonHelp`). The output is a
 * tiny TypeScript file (~3.5 KB) that `setup.ts` injects on the client via
 * `setBlocks()`. Auto-syncs with the admin: re-running `generate:blocks`
 * (or `npm run build`) regenerates `blocks.gen.json`, then this script
 * re-extracts the site-globals subset.
 *
 * Run:
 *   tsx scripts/generate-site-globals.ts
 *
 * Output:
 *   src/server/cms/site-globals.gen.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const INPUT = resolve(process.cwd(), "src/server/cms/blocks.gen.json");
const OUTPUT = resolve(process.cwd(), "src/server/cms/site-globals.gen.ts");

type BlocksRecord = Record<string, unknown>;

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/**
 * Walk a value recursively and collect every string that appears as the
 * value of a `__resolveType` field. Those are the resolution targets the
 * framework will look up by name.
 */
function collectResolveTypeRefs(value: unknown, out: Set<string>): void {
  if (Array.isArray(value)) {
    for (const item of value) collectResolveTypeRefs(item, out);
    return;
  }
  if (!isPlainObject(value)) return;
  for (const [k, v] of Object.entries(value)) {
    if (k === "__resolveType" && typeof v === "string") out.add(v);
    else collectResolveTypeRefs(v, out);
  }
}

/**
 * Compute the transitive closure of block references starting from `site`.
 * A `__resolveType` value is treated as a BLOCK ref only if the value is
 * also a top-level key in `blocks.gen.json`. Section/loader file paths
 * (`site/sections/Foo.tsx`, `website/loaders/bar.ts`) are not blocks — they
 * resolve via the section registry, which is populated independently by
 * `applySectionConventions`.
 */
function closeOverBlockRefs(blocks: BlocksRecord, seedKey: string): Set<string> {
  const needed = new Set<string>([seedKey]);
  const queue: string[] = [seedKey];
  while (queue.length > 0) {
    const key = queue.shift()!;
    const block = blocks[key];
    if (block === undefined) continue;
    const refs = new Set<string>();
    collectResolveTypeRefs(block, refs);
    for (const ref of refs) {
      if (!(ref in blocks)) continue; // not a block — section or loader path
      if (needed.has(ref)) continue;
      needed.add(ref);
      queue.push(ref);
    }
  }
  return needed;
}

function main(): void {
  const raw = readFileSync(INPUT, "utf8");
  const blocks = JSON.parse(raw) as BlocksRecord;

  if (!isPlainObject(blocks.site)) {
    console.error(
      "[generate-site-globals] no `site` key in blocks.gen.json — nothing to do.",
    );
    process.exit(1);
  }

  const needed = closeOverBlockRefs(blocks, "site");
  const subset: BlocksRecord = {};
  // Preserve a stable, readable order: site first, then everything else
  // alphabetically. The generated file is checked into git, so stable
  // ordering avoids unnecessary diffs when extracted.
  const orderedKeys = ["site", ...[...needed].filter((k) => k !== "site").sort()];
  for (const key of orderedKeys) {
    if (!(key in blocks)) continue;
    subset[key] = blocks[key];
  }

  const banner = [
    "// Auto-generated by scripts/generate-site-globals.ts — DO NOT EDIT.",
    "//",
    "// Subset of blocks.gen.json that withSiteGlobals.wrapLoader needs to",
    "// resolve `site.theme + site.global + site.pageSections` on the client.",
    "// Imported by setup.ts and injected via setBlocks() to work around",
    "// decocms/deco-start#233 (framework's vite plugin stubs blocks.gen.ts",
    "// to `{}` on the client bundle).",
    "//",
    "// Re-run `npm run generate:site-globals` after the admin changes any",
    "// of these blocks. Wired into the `build` script so production builds",
    "// always stay in sync.",
    "",
  ].join("\n");

  const body = `export const siteGlobalsBlocks: Record<string, unknown> = ${
    JSON.stringify(subset, null, 2)
  };\n`;

  writeFileSync(OUTPUT, banner + body, "utf8");

  console.log(
    `[generate-site-globals] wrote ${OUTPUT.replace(process.cwd() + "/", "")} ` +
      `with ${Object.keys(subset).length} block(s): ${Object.keys(subset).join(", ")}`,
  );
}

main();
