// Auto-generated by @decocms/start/scripts/generate-sections.ts
// Do not edit manually. Add convention exports to your section files instead.
//
// Supported conventions:
//   export const eager = true       → always SSR'd (never deferred)
//   export const cache = "listing"  → SWR-cached section loader results
//   export const layout = true      → cached as layout (Header, Footer, Theme)
//   export const sync = true        → bundled synchronously (not lazy-loaded)
//   export const clientOnly = true  → skip SSR (client-only rendering)
//   export const seo = true         → SEO section (provides page head data)
//   export function LoadingFallback → skeleton shown while section loads

import * as _sync0 from "../../sections/Blog/BlogAuthors";
import * as _sync1 from "../../sections/Blog/BlogHeader";
import * as _sync2 from "../../sections/Blog/BlogHome";
import * as _sync3 from "../../sections/Blog/BlogPostSection";
import * as _sync4 from "../../sections/Blog/BlogSearch";
import * as _sync5 from "../../sections/Blog/BlogTopics";
import * as _sync6 from "../../sections/Seo/SeoBlogAuthor";
import * as _sync7 from "../../sections/Seo/SeoBlogCategory";
import * as _sync8 from "../../sections/Seo/SeoBlogPost";

export interface SectionMetaEntry {
  eager?: boolean;
  cache?: string;
  layout?: boolean;
  sync?: boolean;
  clientOnly?: boolean;
  seo?: boolean;
  hasLoadingFallback?: boolean;
}

export const sectionMeta: Record<string, SectionMetaEntry> = {
  "site/sections/Blog/BlogAuthors.tsx": { eager: true, sync: true },
  "site/sections/Blog/BlogHeader.tsx": { eager: true, sync: true, layout: true },
  "site/sections/Blog/BlogHome.tsx": { eager: true, sync: true },
  "site/sections/Blog/BlogPostSection.tsx": { eager: true, sync: true },
  "site/sections/Blog/BlogSearch.tsx": { eager: true, sync: true },
  "site/sections/Blog/BlogTopics.tsx": { eager: true, sync: true },
  "site/sections/Seo/SeoBlogAuthor.tsx": { seo: true, sync: true },
  "site/sections/Seo/SeoBlogCategory.tsx": { seo: true, sync: true },
  "site/sections/Seo/SeoBlogPost.tsx": { seo: true, sync: true },
};

export const syncComponents: Record<string, any> = {
  "site/sections/Blog/BlogAuthors.tsx": _sync0,
  "site/sections/Blog/BlogHeader.tsx": _sync1,
  "site/sections/Blog/BlogHome.tsx": _sync2,
  "site/sections/Blog/BlogPostSection.tsx": _sync3,
  "site/sections/Blog/BlogSearch.tsx": _sync4,
  "site/sections/Blog/BlogTopics.tsx": _sync5,
  "site/sections/Seo/SeoBlogAuthor.tsx": _sync6,
  "site/sections/Seo/SeoBlogCategory.tsx": _sync7,
  "site/sections/Seo/SeoBlogPost.tsx": _sync8,
};

export const loadingFallbacks: Record<string, React.ComponentType<any>> = {};
