// Auto-generated by scripts/generate-site-globals.ts — DO NOT EDIT.
//
// Subset of blocks.gen.json that withSiteGlobals.wrapLoader needs to
// resolve `site.theme + site.global + site.pageSections` on the client.
// Imported by setup.ts and injected via setBlocks() to work around
// decocms/deco-start#233 (framework's vite plugin stubs blocks.gen.ts
// to `{}` on the client bundle).
//
// Re-run `npm run generate:site-globals` after the admin changes any
// of these blocks. Wired into the `build` script so production builds
// always stay in sync.
export const siteGlobalsBlocks: Record<string, unknown> = {
  "site": {
    "__resolveType": "site/apps/site.ts",
    "routes": [
      {
        "__resolveType": "website/loaders/pages.ts"
      }
    ],
    "seo": {
      "titleTemplate": "%s | Blog",
      "descriptionTemplate": "%s",
      "type": "website",
      "title": "Blog — Engenharia, Performance, Design e Produto",
      "description": "Artigos sobre engenharia de software, performance web, design de produto e cultura de times.",
      "favicon": "https://ozksgdmyrqcxcwhnbepg.supabase.co/storage/v1/object/public/assets/5018/71c97b9c-b94a-4cf5-8120-4bb7b99b21bb",
      "noIndexing": false
    },
    "global": [],
    "caching": {
      "directives": []
    },
    "firstByteThresholdMS": false
  }
};
